<% # Handle old behaviour of official mysql image %>
<% user = ENV.key?("DATABASE_ROOT_PASSWORD") ? "root" : ENV["DATABASE_USER"] %>
<% password = ENV.key?("DATABASE_ROOT_PASSWORD") ? ENV["DATABASE_ROOT_PASSWORD"] : ENV["DATABASE_PASSWORD"] %>
development:
  adapter: mysql2
  database: sampledb 
  username: <%= user %>
  password: <%= password %>
  host: <%= ENV["DATABASE_SERVICE_HOST"] %>
  port: <%= ENV["DATABASE_SERVICE_PORT"] %>

test:
  adapter: mysql2
  database: sampledb 
  username: <%= user %>
  password: <%= password %>
  host: <%= ENV["DATABASE_TEST_SERVICE_HOST"] %>
  port: <%= ENV["DATABASE_TEST_SERVICE_PORT"] %>

production:
  adapter: mysql2
  database: sampledb
  username: <%= user %>
  password: <%= password %>
  host: <%= ENV["DATABASE_SERVICE_HOST"] %>
  port: <%= ENV["DATABASE_SERVICE_PORT"] %>
